"""Oren et al. 2023 exchangeability (permutation) test for benchmark contamination.

Idea
----
A clean benchmark dataset is *exchangeable*: a model that has not been trained on it has no
reason to prefer one ordering of its examples over another, so the total log-likelihood the
model assigns to the examples is (in distribution) invariant to permutation. If the model was
trained on the benchmark in its **canonical order** (the order it was published / shuffled in
the training corpus), the model memorizes that order and assigns the canonical concatenation a
*higher* total log-likelihood than almost all random permutations. The test compares the
canonical-order log-likelihood against the null distribution generated by random shufflings.

This is NOT a per-text membership detector. It operates on an *ordered set of examples* and
returns a single dataset-level p-value, so it does not implement the
:class:`~detectors.base.Detector` ABC. It does reuse a :class:`~detectors.base.ModelScorer`
(``HFScorer`` / ``MockScorer``) to get log-likelihoods.

Why order must cross example boundaries
---------------------------------------
Per-example sequence log-likelihood (sum of ``TokenStats.token_logprob`` for the example
scored in isolation) is *order-invariant*: summing those over a permutation gives the same
total no matter the order, so it carries no order signal and the test would be vacuous. To make
order matter, each permutation's score is the model log-likelihood of the examples
**concatenated, in that order, into a single string** (joined by ``sep``). Then tokens in one
example are conditioned on the running prefix of the previous examples, exactly the
cross-boundary memorization signal the canonical training order would imprint.

Cost: the concatenation is re-scored once per permutation (``n_permutations`` forward passes).
Keep the example list short and ``n_permutations`` modest on CPU.
"""
from __future__ import annotations

from dataclasses import dataclass
from typing import List, Sequence

import numpy as np

from .base import ModelScorer


@dataclass
class OrenResult:
    """Result of an Oren permutation test."""

    p_value: float
    canonical_loglik: float
    null_mean: float
    null_std: float

    def as_dict(self) -> dict:
        return {
            "p_value": self.p_value,
            "canonical_loglik": self.canonical_loglik,
            "null_mean": self.null_mean,
            "null_std": self.null_std,
        }


class OrenPermutationTest:
    """Permutation (exchangeability) contamination test.

    Parameters
    ----------
    scorer : ModelScorer
        A model scorer (``HFScorer`` for a real LM, ``MockScorer`` for tests). Its
        ``score_tokens(text).token_logprob`` is summed to get the total log-likelihood of a
        concatenated ordering.
    sep : str
        String inserted between consecutive examples when concatenating. Default newline,
        matching how examples typically sit in a serialized benchmark file.
    """

    def __init__(self, scorer: ModelScorer, sep: str = "\n"):
        self.scorer = scorer
        self.sep = sep

    def _ordering_loglik(self, examples: Sequence[str], order: Sequence[int]) -> float:
        """Total model log-likelihood of the examples concatenated in ``order``.

        Order matters because the concatenation is scored as one string, so each example's
        tokens are conditioned on the prefix formed by the earlier examples.
        """
        text = self.sep.join(examples[i] for i in order)
        stats = self.scorer.score_tokens(text)
        return float(np.sum(stats.token_logprob))

    def test(
        self,
        examples: List[str],
        n_permutations: int = 1000,
        seed: int = 0,
    ) -> dict:
        """Run the test on ``examples`` given in their canonical order.

        Parameters
        ----------
        examples : list[str]
            The benchmark examples, in canonical (published / training) order.
        n_permutations : int
            Number of random permutations forming the null distribution.
        seed : int
            RNG seed for reproducible permutations.

        Returns
        -------
        dict with keys ``p_value``, ``canonical_loglik``, ``null_mean``, ``null_std``.

        The one-sided p-value is::

            p = (1 + #{perm : loglik(perm) >= loglik(canonical)}) / (n_permutations + 1)

        Small p => the canonical order is favored beyond chance => evidence of contamination.
        """
        if len(examples) < 2:
            raise ValueError("permutation test needs at least 2 examples")
        if n_permutations < 1:
            raise ValueError("n_permutations must be >= 1")

        rng = np.random.default_rng(seed)
        canonical_order = list(range(len(examples)))
        canonical = self._ordering_loglik(examples, canonical_order)

        null = np.empty(n_permutations, dtype=np.float64)
        ge = 0
        for k in range(n_permutations):
            perm = rng.permutation(len(examples))
            ll = self._ordering_loglik(examples, perm)
            null[k] = ll
            if ll >= canonical:
                ge += 1

        p_value = (1 + ge) / (n_permutations + 1)
        return OrenResult(
            p_value=float(p_value),
            canonical_loglik=float(canonical),
            null_mean=float(null.mean()),
            null_std=float(null.std()),
        ).as_dict()
